[[sni]]
name = "shadowsocks"
inbound = ["www.bing.com","/*.cdndeliver.com"]
outbound = "shadowsocks:443"

#default outbound
[[sni]]
name = "caddy"
inbound = ["/*"]
outbound = "caddy:443"

[global]
qqwry = "czipdata.dat"
ipdb_v6 = "ipv6wry.db"
ipdb_v4 = "czipdata.dat"