[[sni]]
name = "shadowsocks"
inbound = ["www.bing.com","/*.cdndeliver.com"]
outbound = "baidu.com:443"

#default outbound
[[sni]]
name = "caddy"
inbound = ["/*"]
outbound = "baidu.com:443"

[global]
qqwry = "qqwry.dat"
ipdb_v6 = "ipv6wry.db"